### ISSUE TITLE
Getting an Internal error on first install

### ISSUE THREAD

**Issue by FlattusBlastus** [jancborchardt/owncloud-scripts#10]
MGIt was a pain to work with and ultimately didnt work. This worked awesome:
Install (and optionally clone as well) with Termux
First install some dependencies pkg install php php-fpm sqlite coreutils openssl-tool git (I added git)
Allow Termux to access storage outside of own folder termux-setup-storage
(If you want to clone with Termux: cd /storage/emulated/0/ && git clone https://github.com/nextcloud/server.git nextcloud && git clone https://github.com/nextcloud/3rdparty.git nextcloud/3rdparty)
Get the Nextcloud submodules cd /storage/emulated/0/nextcloud/ && git submodule update --init
Start the server php -S 0.0.0.0:8080 -t /storage/emulated/0/nextcloud/
Finish setup in Firefox (For those installing via F-Droid, you will need Fennec)
Go to http://0.0.0.0:8080
Set an admin username and password
(SQLite will be used as database)

That said... the correct perms dont exist for the nextcloud directory. Evidently a chown command is required. However, what account should be used? Can you share a proper chown command and add it right before the Start the server step?

Also, is there a way to make sure that termux doesn't get killed?

**Comment by franco-giordano** [comment]
I'm also experiencing problems with the installation. I dont even get past the Finish Setup screen.

After enabling debug mode I get the following error when clicking 'Finish Setup':
```
Internal Server Error

The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.
Technical details

    Remote Address: [redacted]
    Request ID: YQs6T[...]
    TypeError
    0
    count(): Argument #1 ($value) must be of type Countable|array, bool given
    /storage/emulated/0/nextcloud-srv/lib/private/Http/Client/DnsPinMiddleware.php
    68


Trace

#0 /storage/emulated/0/nextcloud-srv/lib/private/Http/Client/DnsPinMiddleware.php(68): count(false)
#1 /storage/emulated/0/nextcloud-srv/lib/private/Http/Client/DnsPinMiddleware.php(113): OC\Http\Client\DnsPinMiddleware->dnsResolve('apps.nextcloud....', 0)
#2 /storage/emulated/0/nextcloud-srv/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): OC\Http\Client\DnsPinMiddleware->OC\Http\Client\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#3 /storage/emulated/0/nextcloud-srv/3rdparty/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 /storage/emulated/0/nextcloud-srv/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 /storage/emulated/0/nextcloud-srv/3rdparty/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#6 /storage/emulated/0/nextcloud-srv/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#7 /storage/emulated/0/nextcloud-srv/3rdparty/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#8 /storage/emulated/0/nextcloud-srv/3rdparty/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#9 /storage/emulated/0/nextcloud-srv/3rdparty/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync('get', Object(GuzzleHttp\Psr7\Uri), Array)
#10 /storage/emulated/0/nextcloud-srv/lib/private/Http/Client/Client.php(223): GuzzleHttp\Client->request('get', 'https://apps.ne...', Array)
#11 /storage/emulated/0/nextcloud-srv/lib/private/App/AppStore/Fetcher/Fetcher.php(108): OC\Http\Client\Client->get('https://apps.ne...', Array)
#12 /storage/emulated/0/nextcloud-srv/lib/private/App/AppStore/Fetcher/AppFetcher.php(79): OC\App\AppStore\Fetcher\Fetcher->fetch('', '')
#13 /storage/emulated/0/nextcloud-srv/lib/private/App/AppStore/Fetcher/Fetcher.php(180): OC\App\AppStore\Fetcher\AppFetcher->fetch('', '', false)
#14 /storage/emulated/0/nextcloud-srv/lib/private/Installer.php(231): OC\App\AppStore\Fetcher\Fetcher->get(false)
#15 /storage/emulated/0/nextcloud-srv/lib/private/Installer.php(532): OC\Installer->downloadApp('bruteforcesetti...')
#16 /storage/emulated/0/nextcloud-srv/lib/private/Setup.php(407): OC\Installer->installAppBundle(Object(OC\App\AppStore\Bundles\CoreBundle))
#17 /storage/emulated/0/nextcloud-srv/core/Controller/SetupController.php(74): OC\Setup->install(Array)
#18 /storage/emulated/0/nextcloud-srv/lib/base.php(937): OC\Core\Controller\SetupController->run(Array)
#19 /storage/emulated/0/nextcloud-srv/index.php(36): OC::handleRequest()
#20 {main}

```

By installing with `pkg install php` it is using PHP 8.0, I dont know if that's part of the problem

Thanks!

**Comment by sharicov** [comment]
Getting same issue as  franco-giordano don't even get past the Finish Setup screen.

**Comment by rifazn** [comment]
Having the exact same problem as @FlattusBlastus. Anyone managed to progress further yet?

**Comment by rifazn** [comment]
Update: Tried with php7 and its working no problems now (not including `php -S` being very slow).

Termux supports downloading php7 with: `pkg install php7`

**Comment by jancborchardt** [comment]
@rifazn is php7 meanwhile the normal installation candidate when doing `pkg install php` as well? Otherwise a pull request is welcome. :)
